apiVersion: dotnetes.dot.net/v1alpha1
kind: DotNetApp
metadata:
  name: "!APPNAME!"
  labels:
    "dotnetes.dot.net/dotnetes": 1
    "dotnetes.dot.net/app": "!APPNAME!"
spec:
  image: "!APPIMAGE!"
  replicas: 1
