# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
images:
  - name: appcontainer # match images with this name
    newTag: e475530a06234a6381da7f7074158f5b # override the tag
    newName: anursedotnetes.azurecr.io/helloworld/app # override the name
commonLabels:
    "cloud.dot.net/app": helloworld # Kustomize will replace this
namePrefix: helloworld-
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress
    path: patch-ingress.yaml