apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dotnetapps.dotnetes.dot.net
spec:
  group: dotnetes.dot.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: dotnetapps
    singular: dotnetapp
    kind: DotNetApp
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            image:
              type: string
            replicas:
              type: integer
