apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetes-operator
  namespace: dotnetes-system
  labels:
    "dotnetes.dot.net/dotnetes": "1"
spec:
  selector:
    matchLabels:
      app: dotnetes-operator
  template:
    metadata:
      labels:
        app: dotnetes-operator
    spec:
      containers:
      - name: dotnetes-operator
        image: anursedotnetes.azurecr.io/dotnetes/operator